import type { SectorProfile } from "./types.js";

export const COACH_SECTOR: SectorProfile = {
  key: "coach",
  labels: [
    "coach", "coaching", "life coach", "business coach", "bien-etre",
    "developpement personnel", "PNL", "hypnose",
  ],
  positioning: "Le coach se distingue du consultant par la nature de sa valeur : il ne donne pas des solutions, il fait emerger la transformation chez le client. Le positionnement gagnant ne dit pas 'je suis coach certifie' — il dit 'j'accompagne les dirigeants de PME a traverser les transitions qui bloquent leur croissance'. La certification est une condition necessaire, pas un argument de vente. Le vrai differenciateur est la specialisation par population (dirigeants, managers, reconversion) ou par problematique (leadership, confiance, equilibre). Le coach generique qui 'accompagne tout le monde' n'accompagne personne — parce que le client veut quelqu'un qui comprend SA realite specifique, pas un generaliste bienveillant.",
  offerStructure: "Offre d'entree : session decouverte gratuite de 30 min — pas un coaching, une conversation qui fait realiser au prospect qu'il a besoin d'un accompagnement structure. L'objectif n'est pas de resoudre en 30 min, c'est de faire sentir la difference entre tourner en rond seul et avancer avec un guide. Offre coeur : programme de coaching sur 3-6 mois avec seances bi-mensuelles, exercices entre les sessions, et points de mesure de progression. Le cadre temporel defini evite la dependance et demontre la confiance dans la methode. Offre premium : accompagnement intensif avec acces illimite (Voxer/WhatsApp), retraite annuelle, et communaute d'alumni. L'upsell naturel est le passage du coaching individuel au coaching de groupe ou a la formation de coachs internes.",
  priorityChannels: ["Instagram", "podcasts (invitations et podcast propre)", "temoignages clients video", "communaute et groupe prive"],
  pricingStrategy: "Le coaching se tarifie a la transformation, JAMAIS a la seance. '150EUR la seance' est une commodite comparable a n'importe quel autre coach. 'Programme de 6 mois qui vous fait passer de manager epuise a leader inspirant — investissement de 5000EUR' est une transformation qui n'a pas de prix comparable. L'ancrage se fait par le cout de la stagnation : 'Combien vous coute chaque mois de plus dans cette situation ? En burn-out potentiel, en opportunites manquees, en impact sur votre equipe ?' Le prospect doit calculer lui-meme que le prix du coaching est derisoire face au prix de l'inaction. Proposer un paiement echelonne pour reduire la friction — pas comme une remise, mais comme un investissement mensuel dans sa propre croissance.",
  storytellingAngle: "Le coach qui a traverse sa propre transformation. L'authenticite est la monnaie du coaching — le client veut savoir que son coach n'est pas un theoricien qui recite des techniques, mais quelqu'un qui a vecu le doute, le blocage, la percee. Le recit fondateur type : 'Il y a 5 ans, j'etais exactement la ou vous etes. Voici ce qui a change, et comment j'ai structure cette experience en methode pour accompagner d'autres.' Les temoignages clients sont l'arme nucleaire du coach — pas des temoignages generiques ('super coaching'), mais des recits de transformation avec le avant/apres concret : 'Avant le coaching, je n'arrivais pas a deleguer et je travaillais 70h/semaine. 6 mois apres, j'ai une equipe autonome et je travaille 40h avec un CA en hausse de 30%.'",
  clientSizeAdaptation: {
    small: "Solopreneurs et independants : coaching individuel intensif avec focus sur les blocages qui freinent directement le CA. Programmes de groupe pour rendre le coaching accessible. Formats hybrides (sessions live + contenus en autonomie) pour maximiser l'impact par euro investi. Le solopreneur a besoin de resultats tangibles rapidement — pas de travail sur soi abstrait, mais des prises de conscience qui se traduisent en actions business concretes dans la semaine.",
    medium: "PME et dirigeants : coaching de leadership et de management. Le coach se positionne comme le confident strategique que le dirigeant n'a pas en interne — la personne a qui on peut dire ce qu'on ne dit ni a son equipe, ni a ses associes, ni a son conjoint. Programmes de coaching d'equipe pour les transitions (reorganisation, croissance rapide, crise). Retainers semestriels avec mesure d'impact sur les KPIs de l'equipe.",
    large: "Grands comptes : programmes de coaching pour le comite de direction et les hauts potentiels. Se positionner comme specialiste de la transformation organisationnelle par le coaching individuel. Proposer des cohortes de coaching avec mesure d'impact collective. Le coach devient partenaire RH sur les sujets de leadership, d'engagement et de retention des talents cles.",
  },
};
