import type { SectorProfile } from "./types.js";

export const MARKETER_SECTOR: SectorProfile = {
  key: "marketer",
  labels: [
    "marketeur", "marketing", "growth", "acquisition", "SEA", "SEO",
    "social media", "community manager", "growth hacker",
  ],
  positioning: "Le marketeur freelance est dans une position paradoxale : il vend du marketing a des gens qui pensent savoir faire du marketing. Le positionnement gagnant ne parle pas de 'strategie marketing' — il parle de resultats mesurables dans un domaine precis. 'J'aide les SaaS B2B a reduire leur CAC de 40% en 90 jours' bat 'Consultant marketing digital' a chaque fois. La specialisation par canal (SEA, SEO, LinkedIn Ads) ou par metrique (CAC, LTV, ROAS) cree une expertise pointue que les equipes internes generalistes ne peuvent pas reproduire. Le marketeur freelance qui maitrise un canal mieux que n'importe quel employe interne devient irreplacable — pas parce qu'il est moins cher, mais parce qu'il a vu 50 comptes la ou l'interne n'en a vu qu'un.",
  offerStructure: "Offre d'entree : audit marketing express avec benchmark concurrentiel et 5 quick wins actionnables — demontre la profondeur analytique et cree l'urgence ('vous depensez 30% de votre budget sur des mots-cles qui ne convertissent pas'). Offre coeur : accompagnement mensuel avec objectifs KPI, reportings hebdo, et optimisation continue d'un canal principal. Le marketeur gere, mesure et itere — le client voit les chiffres monter. Offre premium : direction marketing externalisee avec strategie multi-canal, coordination des prestataires (designer, redacteur, dev) et reporting C-level. L'upsell naturel est la formation de l'equipe interne pour qu'elle prenne le relais sur les campagnes recurrentes tandis que le marketeur se concentre sur l'experimentation et la strategie.",
  priorityChannels: ["LinkedIn", "conferences et meetups marketing", "etudes de cas publiees", "partenariats avec agences et SaaS complementaires"],
  pricingStrategy: "Le marketeur qui facture un TJM est un employe deguise. Le marketeur qui facture au resultat est un partenaire. La structure ideale : une base fixe mensuelle (retainer) + un variable lie aux KPIs (bonus si CAC < seuil, si ROAS > cible). Cette structure aligne les interets et prouve la confiance dans sa propre expertise. L'ancrage se fait par le budget media gere : gerer 50K/mois de budget ads pour 5K/mois d'honoraires, c'est 10% — la norme agence est 15-20%. Le freelance est MOINS cher ET plus performant parce qu'il n'a pas la structure d'une agence a nourrir. Toujours presenter le cout de l'inaction : 'Chaque mois sans optimisation, vous perdez X EUR en budget media gaspille.'",
  storytellingAngle: "Le marketeur qui joue avec son propre argent. Le recit le plus puissant pour un marketeur freelance est de montrer ce qu'il a construit pour LUI-MEME : son propre pipeline d'acquisition, sa propre strategie de contenu, ses propres metrics. Si le marketeur ne sait pas se marketer, pourquoi le client lui ferait-il confiance ? Les etudes de cas doivent aller au-dela des vanity metrics : pas 'impressions en hausse de 200%', mais 'pipeline qualifie en hausse de 200%, avec un CAC en baisse de 30%'. Le storytelling du marketeur est data-driven par nature — chaque affirmation est soutenue par un chiffre, chaque recommandation par un test.",
  clientSizeAdaptation: {
    small: "Startups et solopreneurs : audit + mise en place d'un canal d'acquisition principal avec budget maitrise. Focus sur le product-market fit marketing : trouver LE message et LE canal qui convertit avant de scaler. Pas de strategie 360 — une seule fleche bien aimee. Templates de campagnes reutilisables pour l'autonomie.",
    medium: "PME : strategie multi-canal avec priorisation budget. Mise en place de tableaux de bord analytics pour suivre le ROI en temps reel. Formation de l'equipe interne sur l'execution quotidienne pendant que le freelance pilote la strategie et l'experimentation. Retainers trimestriels avec revue strategique mensuelle.",
    large: "Grands comptes : positionnement comme expert canal ou expert secteur que l'equipe interne n'a pas. Audit des campagnes existantes avec recommandations de restructuration. Pilotage de projets specifiques (lancement produit, penetration nouveau marche, restructuration ads) avec objectifs et timeline definis. Integration avec les equipes et les outils existants, pas de rupture.",
  },
};
