import type { SectorProfile } from "./types.js";

export const SAAS_FOUNDER_SECTOR: SectorProfile = {
  key: "saas_founder",
  labels: [
    "saas", "startup", "founder", "fondateur", "product", "PLG",
    "product-led", "MRR", "churn", "trial",
  ],
  positioning: "Le fondateur SaaS ne cherche pas un freelance — il cherche un co-pilote growth qui comprend les metriques qui comptent : MRR, churn, LTV, CAC, NRR. Le positionnement gagnant parle le langage du SaaS : 'J'aide les SaaS B2B entre 10K et 100K MRR a passer de growth hacking chaotique a growth engine previsible.' Le freelance qui travaille avec un SaaS founder doit comprendre que chaque euro depense en acquisition doit etre recuperable en moins de 12 mois — sinon c'est un trou noir. La specialisation par stade (pre-PMF, post-PMF, scale) ou par modele (PLG, sales-led, hybrid) cree un niveau de pertinence que les agences generalistes ne peuvent pas atteindre.",
  offerStructure: "Offre d'entree : audit funnel complet (landing → trial → activation → conversion → retention) avec identification des fuites et quick wins — le SaaS founder voit immediatement les points ou il perd de l'argent. Offre coeur : accompagnement growth sur 3 mois avec experimentation structuree (2-3 tests/semaine), dashboard de suivi, et focus sur UNE metrique North Star (generalement l'activation pour les early-stage, la retention pour les scale). Offre premium : direction growth externalisee avec strategie multi-canal, coordination equipe produit/marketing, et reporting board-ready. L'upsell naturel est la mise en place d'une growth team interne structuree avec process et playbooks.",
  priorityChannels: ["Product Hunt", "Twitter/X", "communaute produit et fondateurs", "content marketing (blog, newsletter)"],
  pricingStrategy: "Le SaaS founder pense en multiples et en payback period. Le pricing doit parler ce langage. 'Retainer de 5K/mois' est abstrait. '5K/mois pour reduire le churn de 2% — ce qui represente 20K/mois de MRR sauve, soit un ROI de 4x des le premier mois' est un no-brainer. La structure ideale pour un SaaS : base fixe + variable lie au delta MRR ou au delta churn. Cela aligne les interets et prouve que le freelance croit en sa propre capacite a delivrer. L'ancrage par le cout de la non-action : 'Chaque mois a 5% de churn mensuel, c'est 50% de votre base annualisee qui disparait. Passer a 3% change tout — et c'est exactement ce qu'on vise.' Toujours presenter les projections sur 12 mois pour montrer l'effet compose.",
  storytellingAngle: "Le growth practitioner qui a vecu les memes galeres. Le SaaS founder respecte ceux qui ont deja ete dans les tranchees — qui ont lance des features a minuit, qui ont regarde le churn monter avec une boule au ventre, qui ont pivote trois fois avant de trouver le canal qui scale. Le storytelling ideal melange donnees et recit : 'Quand on a travaille avec [SaaS similaire], leur trial-to-paid etait a 4%. En 8 semaines d'experimentation sur l'onboarding, on l'a pousse a 11%. Voici comment.' Les metriques sont le language natif du SaaS founder — chaque affirmation doit etre soutenue par un chiffre, chaque recommandation par un test. Le contenu qui attire les SaaS founders est educational et specifique : pas 'comment faire du growth', mais '3 tactiques pour reduire le churn des comptes enterprise sans toucher au produit'.",
  clientSizeAdaptation: {
    small: "Pre-seed / Seed (0-10K MRR) : focus sur le product-market fit et l'acquisition des 100 premiers utilisateurs payants. Pas de strategie multi-canal — un seul canal valide a fond. Le freelance aide a identifier le canal (souvent outbound + communaute) et a iterer sur le message jusqu'au signal de traction. Budget serre = creativite maximale. Pas de vanity metrics — seules les conversions comptent.",
    medium: "Series A (10K-100K MRR) : le SaaS a trouve son PMF, il faut maintenant scaler l'acquisition de maniere previsible. Mise en place de la growth machine : funnel automatise, scoring, sequences de nurturing, et tests A/B systematiques. Le freelance structure les process pour que l'equipe interne puisse executer. Focus sur l'activation et la retention — acquerir sans retenir, c'est remplir un seau perce.",
    large: "Series B+ (100K+ MRR) : le SaaS a une equipe growth interne mais manque d'expertise specifique (PLG, enterprise sales, expansion revenue). Le freelance se positionne comme expert de niche qui accelere un workstream specifique. Audit des metriques existantes, identification des leviers de croissance inexploites, et mise en place de playbooks replicables. Integration avec les equipes produit, sales et CS pour une approche cross-fonctionnelle.",
  },
};
